"use client"

import { DashboardHeader } from "@/components/dashboard-header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import {
  Download,
  Search,
  CheckCircle2,
  XCircle,
  Clock,
  Loader2,
  FileText,
  Eye,
  Users,
  AlertCircle,
  Save,
} from "lucide-react"
import { useState, useEffect, useRef } from "react"
import { useRouter } from "next/navigation"
import { getCustomerNameByJobId, getPhoneNumberByJobId } from "@/lib/call-memory"
import { createBrowserClient } from "@/lib/supabase/client"

interface CallRecord {
  id: string
  customerName: string
  phoneNumber: string
  date: string
  time: string
  duration: string
  status: string
  type: string
  hasReport: boolean
  score?: number
  mood?: string
  notes?: string
}

interface CallReport {
  id: string
  notes: string
}

const CUSTOMER_MOODS = {
  happy: { label: "Happy", color: "bg-green-500/20 text-green-600 border-green-500/30" },
  satisfied: { label: "Satisfied", color: "bg-blue-500/20 text-blue-600 border-blue-500/30" },
  neutral: { label: "Neutral", color: "bg-gray-500/20 text-gray-600 border-gray-500/30" },
  frustrated: { label: "Frustrated", color: "bg-orange-500/20 text-orange-600 border-orange-500/30" },
  angry: { label: "Angry", color: "bg-red-500/20 text-red-600 border-red-500/30" },
}

export default function CustomerRecordsPage() {
  const [searchQuery, setSearchQuery] = useState("")
  const [statusFilter, setStatusFilter] = useState("all")
  const [sortFilter, setSortFilter] = useState("newest")
  const [records, setRecords] = useState<CallRecord[]>([])
  const [filteredRecords, setFilteredRecords] = useState<CallRecord[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [generatingReportId, setGeneratingReportId] = useState<string | null>(null)
  const [editingNotes, setEditingNotes] = useState<{ id: string; notes: string } | null>(null)
  const [isNotesDialogOpen, setIsNotesDialogOpen] = useState(false)
  const autoGeneratedReports = useRef(new Set<string>())
  const router = useRouter()

  useEffect(() => {
    fetchCustomerRecords()
  }, [])

  useEffect(() => {
    const savedRecords = localStorage.getItem("customer-records")
    if (savedRecords) {
      try {
        const parsed = JSON.parse(savedRecords)
        setRecords((current) => {
          const merged = [...current]
          parsed.forEach((saved: CallRecord) => {
            const index = merged.findIndex((r) => r.id === saved.id)
            if (index >= 0) {
              merged[index] = { ...merged[index], ...saved }
            }
          })
          return merged
        })
      } catch (error) {
        console.error("[v0] Error loading saved records:", error)
      }
    }
  }, [])

  useEffect(() => {
    if (records.length > 0) {
      const dataToSave = records.map((r) => ({
        id: r.id,
        hasReport: r.hasReport,
        score: r.score,
        mood: r.mood,
        notes: r.notes,
      }))
      localStorage.setItem("customer-records", JSON.stringify(dataToSave))
    }
  }, [records])

  async function fetchCustomerRecords() {
    try {
      // Load from local storage only
      const savedReports = JSON.parse(localStorage.getItem("call-reports") || "[]")
      console.log("[v0] Loaded reports from local storage:", savedReports?.length || 0)

      const response = await fetch("/api/hamsa/jobs?limit=100")
      if (response.ok) {
        const data = await response.json()
        const jobs = data.data?.jobs || []

        const transformedRecords = jobs
          .map((job: any) => {
            const customerNameFromMemory = getCustomerNameByJobId(job.id)
            const phoneNumberFromMemory = getPhoneNumberByJobId(job.id)

            if (!customerNameFromMemory) {
              return null
            }

            const startTime = new Date(job.createdAt)
            const durationInSeconds = job.duration || 0
            const minutes = Math.floor(durationInSeconds / 60)
            const seconds = durationInSeconds % 60

            let callStatus = "in-progress"
            const hamsaStatus = (job.status || "").toUpperCase()

            if (hamsaStatus === "COMPLETED" || hamsaStatus === "SUCCEEDED") {
              callStatus = "completed"
            } else if (hamsaStatus === "FAILED" || hamsaStatus === "ERROR") {
              callStatus = "failed"
            } else if (
              hamsaStatus === "NO_ANSWER" ||
              hamsaStatus === "NO-ANSWER" ||
              hamsaStatus === "NOANSWER" ||
              hamsaStatus === "UNANSWERED"
            ) {
              callStatus = "no-answer"
            } else if (hamsaStatus === "CANCELLED" || hamsaStatus === "CANCELED") {
              callStatus = "cancelled"
            } else if (hamsaStatus === "PENDING" || hamsaStatus === "QUEUED") {
              callStatus = "pending"
            } else if (
              hamsaStatus === "IN-PROGRESS" ||
              hamsaStatus === "IN_PROGRESS" ||
              hamsaStatus === "RUNNING" ||
              hamsaStatus === "ACTIVE"
            ) {
              callStatus = "in-progress"
            }

            const savedReport = savedReports?.find((r) => r.id === job.id || r.call_id === job.id)
            const existingReports = JSON.parse(localStorage.getItem("call-reports") || "[]")
            const localReport = existingReports.find((r: any) => r.id === job.id || r.callId === job.id)

            const reportExists = !!(savedReport || localReport)
            const reportData = savedReport || localReport

            return {
              id: job.id,
              customerName: customerNameFromMemory,
              phoneNumber: phoneNumberFromMemory || job.customer?.number || "N/A",
              date: startTime.toISOString().split("T")[0],
              time: startTime.toTimeString().slice(0, 5),
              duration: `${minutes.toString().padStart(2, "0")}:${seconds.toString().padStart(2, "0")}`,
              status: callStatus,
              type: "outbound",
              hasReport: reportExists,
              score: reportData?.analysis?.customerOverallScore,
              mood: reportData?.analysis?.customerMood,
              notes: reportData?.notes || "",
            }
          })
          .filter((record) => record !== null)

        // Merge with saved reports from local storage
        const localReports = savedReports
          .filter((report: any) => !transformedRecords.find((r) => r.id === report.id))
          .map((report: any) => ({
            id: report.id || report.callId,
            customerName: report.customerName || "Unknown",
            phoneNumber: report.phoneNumber || "N/A",
            date: new Date(report.created_at || report.createdAt || Date.now()).toISOString().split("T")[0],
            time: new Date(report.created_at || report.createdAt || Date.now()).toTimeString().slice(0, 5),
            duration: report.duration || "0:00",
            status: "completed",
            type: "outbound",
            hasReport: true,
            score: report.analysis?.customerOverallScore,
            mood: report.analysis?.customerMood,
            notes: report.notes || "",
          }))

        setRecords([...transformedRecords, ...localReports])
        setFilteredRecords([...transformedRecords, ...localReports])
      }
    } catch (error) {
      console.error("[v0] Error fetching customer records:", error)
    } finally {
      setIsLoading(false)
    }
  }

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "completed":
        return <CheckCircle2 className="h-4 w-4 text-success" />
      case "failed":
        return <XCircle className="h-4 w-4 text-destructive" />
      case "no-answer":
        return <XCircle className="h-4 w-4 text-warning" />
      case "cancelled":
        return <XCircle className="h-4 w-4 text-muted-foreground" />
      case "pending":
        return <Clock className="h-4 w-4 text-warning" />
      case "in-progress":
        return <Loader2 className="h-4 w-4 text-primary animate-spin" />
      default:
        return <Clock className="h-4 w-4 text-muted-foreground" />
    }
  }

  const getStatusBadge = (status: string) => {
    const variants: Record<string, string> = {
      completed: "bg-success/20 text-success border-success/30",
      failed: "bg-destructive/20 text-destructive border-destructive/30",
      "no-answer": "bg-warning/20 text-warning border-warning/30",
      cancelled: "bg-muted text-muted-foreground border-muted",
      pending: "bg-warning/20 text-warning border-warning/30",
      "in-progress": "bg-primary/20 text-primary border-primary/30",
    }
    return variants[status] || "bg-muted text-muted-foreground border-muted"
  }

  const statusCounts = {
    total: records.length,
    completed: records.filter((r) => r.status === "completed").length,
    inProgress: records.filter((r) => r.status === "in-progress" || r.status === "pending").length,
    urgent: records.filter((r) => r.status === "failed" || r.status === "no-answer").length,
  }

  useEffect(() => {
    const autoGenerateReports = async () => {
      for (const record of records) {
        if (
          record.status === "completed" &&
          !record.hasReport &&
          !autoGeneratedReports.current.has(record.id) &&
          !generatingReportId
        ) {
          console.log("[v0] Auto-generating report for completed call:", record.id)
          autoGeneratedReports.current.add(record.id)

          await handleGenerateReport(record.id, record)

          break
        }
      }
    }

    if (records.length > 0) {
      autoGenerateReports()
    }
  }, [records, generatingReportId])

  useEffect(() => {
    let filtered = [...records]

    // Apply search filter
    if (searchQuery) {
      filtered = filtered.filter(
        (record) =>
          record.customerName.toLowerCase().includes(searchQuery.toLowerCase()) ||
          record.phoneNumber.includes(searchQuery),
      )
    }

    // Apply status filter
    if (statusFilter !== "all") {
      filtered = filtered.filter((record) => record.status === statusFilter)
    }

    // Apply sort
    filtered.sort((a, b) => {
      const dateA = new Date(`${a.date} ${a.time}`).getTime()
      const dateB = new Date(`${b.date} ${b.time}`).getTime()
      return sortFilter === "newest" ? dateB - dateA : dateA - dateB
    })

    setFilteredRecords(filtered)
  }, [records, searchQuery, statusFilter, sortFilter])

  const handleGenerateReport = async (callId: string, recordData?: CallRecord) => {
    setGeneratingReportId(callId)
    try {
      console.log("[v0] Generating report for:", callId, "with record data:", recordData)

      const response = await fetch("/api/reports/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ callId }),
      })

      if (response.ok) {
        const report = await response.json()
        console.log("[v0] Generated report:", report)

        const completeReport = {
          ...report,
          customerName: recordData?.customerName || report.customerName || getCustomerNameByJobId(callId) || "Unknown",
          phoneNumber: recordData?.phoneNumber || report.phoneNumber || getPhoneNumberByJobId(callId) || "N/A",
          duration: recordData?.duration || report.duration || "0:00",
          status: "completed", // Always set to completed when report is generated
        }

        console.log("[v0] Complete report with merged data:", completeReport)

        // Save to localStorage
        // Save to localStorage only
        const existingReports = JSON.parse(localStorage.getItem("call-reports") || "[]")
        const updatedReports = [completeReport, ...existingReports.filter((r: any) => r.id !== callId)]
        localStorage.setItem("call-reports", JSON.stringify(updatedReports))
        console.log("[v0] Report saved to local storage successfully")

        const moodFromAnalysis =
          completeReport.analysis?.customerMood ||
          determineMoodFromScore(completeReport.analysis?.customerOverallScore || 5)

        setRecords((current) =>
          current.map((r) =>
            r.id === callId
              ? {
                  ...r,
                  customerName: completeReport.customerName,
                  phoneNumber: completeReport.phoneNumber,
                  duration: completeReport.duration,
                  status: "completed",
                  hasReport: true,
                  score: completeReport.analysis?.customerOverallScore,
                  mood: moodFromAnalysis,
                }
              : r,
          ),
        )

        router.push(`/reports/${callId}`)
      } else {
        const errorText = await response.text()
        console.error("[v0] Failed to generate report:", errorText)
        alert("Failed to generate report. Please try again.")
      }
    } catch (error) {
      console.error("[v0] Error generating report:", error)
      alert("Error generating report. Please try again.")
    } finally {
      setGeneratingReportId(null)
    }
  }

  const determineMoodFromScore = (score: number): string => {
    if (score >= 9) return "happy"
    if (score >= 7) return "satisfied"
    if (score >= 5) return "neutral"
    if (score >= 3) return "frustrated"
    return "angry"
  }

  const handleNotesUpdate = (callId: string, notes: string) => {
    setEditingNotes({ id: callId, notes })
    setIsNotesDialogOpen(true)
  }

  const handleSaveNotes = async () => {
    if (!editingNotes) return

    try {
      // Save only to local storage
      const existingReports = JSON.parse(localStorage.getItem("call-reports") || "[]")
      const updatedReports = existingReports.map((r: any) =>
        r.id === editingNotes.id || r.callId === editingNotes.id ? { ...r, notes: editingNotes.notes } : r,
      )
      localStorage.setItem("call-reports", JSON.stringify(updatedReports))

      setRecords((current) => current.map((r) => (r.id === editingNotes.id ? { ...r, notes: editingNotes.notes } : r)))

      setIsNotesDialogOpen(false)
      setEditingNotes(null)
    } catch (error) {
      console.error("[v0] Error saving notes:", error)
      alert("Failed to save notes. Please try again.")
    }
  }

  const loadRecords = () => {
    fetchCustomerRecords()
  }

  return (
    <div className="h-screen flex flex-col bg-background">
      <DashboardHeader />
      <main className="flex-1 overflow-y-auto p-6">
        <div className="mb-6">
          <h1 className="font-sans text-3xl font-bold text-foreground">Customer Records</h1>
          <p className="mt-1 font-sans text-sm text-muted-foreground">
            Complete record of all customer interactions with detailed analytics and social assessment
          </p>
        </div>

        <div className="mb-6 grid gap-6 md:grid-cols-4">
          <Card className="bg-card">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-sans text-sm font-medium text-muted-foreground">Total Customers</p>
                  <h3 className="mt-2 font-sans text-3xl font-bold text-card-foreground">{statusCounts.total}</h3>
                </div>
                <div className="rounded-lg bg-primary/10 p-3">
                  <Users className="h-6 w-6 text-primary" />
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-card">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-sans text-sm font-medium text-muted-foreground">Completed</p>
                  <h3 className="mt-2 font-sans text-3xl font-bold text-success">{statusCounts.completed}</h3>
                </div>
                <div className="rounded-lg bg-success/10 p-3">
                  <CheckCircle2 className="h-6 w-6 text-success" />
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-card">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-sans text-sm font-medium text-muted-foreground">In Progress</p>
                  <h3 className="mt-2 font-sans text-3xl font-bold text-primary">{statusCounts.inProgress}</h3>
                </div>
                <div className="rounded-lg bg-primary/10 p-3">
                  <Clock className="h-6 w-6 text-primary" />
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-card">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-sans text-sm font-medium text-muted-foreground">Urgent</p>
                  <h3 className="mt-2 font-sans text-3xl font-bold text-destructive">{statusCounts.urgent}</h3>
                </div>
                <div className="rounded-lg bg-destructive/10 p-3">
                  <AlertCircle className="h-6 w-6 text-destructive" />
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <Card className="mb-6 bg-card">
          <CardContent className="p-4">
            <div className="flex flex-wrap gap-4">
              <div className="flex-1 min-w-[300px]">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    placeholder="Search by customer name or phone number..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-10 font-sans"
                  />
                </div>
              </div>
              <Select value={statusFilter} onValueChange={setStatusFilter}>
                <SelectTrigger className="w-[180px] font-sans">
                  <SelectValue placeholder="All Statuses" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Statuses</SelectItem>
                  <SelectItem value="completed">Completed</SelectItem>
                  <SelectItem value="pending">Pending</SelectItem>
                  <SelectItem value="in-progress">In Progress</SelectItem>
                  <SelectItem value="no-answer">No Answer</SelectItem>
                  <SelectItem value="failed">Failed</SelectItem>
                </SelectContent>
              </Select>
              <Select value={sortFilter} onValueChange={setSortFilter}>
                <SelectTrigger className="w-[180px] font-sans">
                  <SelectValue placeholder="Newest First" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="newest">Newest First</SelectItem>
                  <SelectItem value="oldest">Oldest First</SelectItem>
                </SelectContent>
              </Select>
              <Button variant="outline" className="gap-2 bg-transparent">
                <Download className="h-4 w-4" />
                Export CSV
              </Button>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card">
          <CardHeader>
            <CardTitle className="font-sans text-xl font-semibold text-card-foreground">
              Customers ({filteredRecords.length})
            </CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="flex h-64 items-center justify-center">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
              </div>
            ) : filteredRecords.length === 0 ? (
              <div className="flex h-64 items-center justify-center">
                <p className="font-sans text-sm text-muted-foreground">
                  {searchQuery || statusFilter !== "all" ? "No customers match the filters" : "No customers found"}
                </p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow className="border-border hover:bg-transparent">
                      <TableHead className="font-sans font-semibold text-foreground">Customer Name</TableHead>
                      <TableHead className="font-mono text-sm text-muted-foreground">Phone Number</TableHead>
                      <TableHead className="font-sans text-sm text-foreground">Date & Time</TableHead>
                      <TableHead className="font-mono text-sm text-foreground">Duration</TableHead>
                      <TableHead className="font-sans font-semibold text-foreground">Status</TableHead>
                      <TableHead className="font-sans font-semibold text-foreground">Customer Mood</TableHead>
                      <TableHead className="font-sans font-semibold text-foreground">Report</TableHead>
                      <TableHead className="font-sans font-semibold text-foreground">Score</TableHead>
                      <TableHead className="font-sans font-semibold text-foreground">Notes</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredRecords.map((record) => (
                      <TableRow key={record.id} className="border-border">
                        <TableCell className="font-sans font-medium text-foreground">{record.customerName}</TableCell>
                        <TableCell className="font-mono text-sm text-muted-foreground">{record.phoneNumber}</TableCell>
                        <TableCell className="font-sans text-sm text-foreground">
                          <div>{record.date}</div>
                          <div className="text-xs text-muted-foreground">{record.time}</div>
                        </TableCell>
                        <TableCell className="font-mono text-sm text-foreground">{record.duration}</TableCell>
                        <TableCell>
                          <Badge variant="outline" className={getStatusBadge(record.status)}>
                            <span className="flex items-center gap-1.5">
                              {getStatusIcon(record.status)}
                              {record.status === "completed"
                                ? "Completed"
                                : record.status === "failed"
                                  ? "Failed"
                                  : record.status === "no-answer"
                                    ? "No Answer"
                                    : record.status === "cancelled"
                                      ? "Cancelled"
                                      : record.status === "pending"
                                        ? "Pending"
                                        : "In Progress"}
                            </span>
                          </Badge>
                        </TableCell>
                        <TableCell>
                          {record.mood && record.hasReport ? (
                            <Badge
                              variant="outline"
                              className={CUSTOMER_MOODS[record.mood as keyof typeof CUSTOMER_MOODS].color}
                            >
                              {CUSTOMER_MOODS[record.mood as keyof typeof CUSTOMER_MOODS].label}
                            </Badge>
                          ) : (
                            <span className="text-xs text-muted-foreground">-</span>
                          )}
                        </TableCell>
                        <TableCell>
                          {record.hasReport ? (
                            <Button
                              variant="ghost"
                              size="sm"
                              className="gap-2"
                              onClick={() => router.push(`/reports/${record.id}`)}
                            >
                              <Eye className="h-4 w-4" />
                              View Report
                            </Button>
                          ) : (
                            <Button
                              variant="ghost"
                              size="sm"
                              className="gap-2"
                              onClick={() => handleGenerateReport(record.id, record)}
                              disabled={generatingReportId === record.id || record.status !== "completed"}
                            >
                              {generatingReportId === record.id ? (
                                <>
                                  <Loader2 className="h-4 w-4 animate-spin" />
                                  Generating...
                                </>
                              ) : (
                                <>
                                  <FileText className="h-4 w-4" />
                                  Generate Report
                                </>
                              )}
                            </Button>
                          )}
                        </TableCell>
                        <TableCell>
                          {record.score && record.hasReport ? (
                            <div className="text-center">
                              <div className="text-lg font-bold text-primary">{record.score}/10</div>
                            </div>
                          ) : (
                            <span className="text-xs text-muted-foreground">-</span>
                          )}
                        </TableCell>
                        <TableCell>
                          <Button
                            variant="outline"
                            size="sm"
                            className="gap-2 bg-transparent"
                            onClick={() => handleNotesUpdate(record.id, record.notes || "")}
                          >
                            {record.notes ? (
                              <span className="max-w-[100px] truncate">{record.notes}</span>
                            ) : (
                              "Add Notes"
                            )}
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </CardContent>
        </Card>
      </main>
      <Dialog open={isNotesDialogOpen} onOpenChange={setIsNotesDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Notes for {editingNotes ? editingNotes.customerName : "Customer"}</DialogTitle>
            <DialogDescription>Add or edit notes for this customer interaction</DialogDescription>
          </DialogHeader>
          <Textarea
            placeholder="Enter notes here..."
            value={editingNotes ? editingNotes.notes : ""}
            onChange={(e) => setEditingNotes({ ...editingNotes!, notes: e.target.value })}
            rows={5}
          />
          <Button onClick={handleSaveNotes} className="mt-4">
            <Save className="h-4 w-4 mr-2" />
            Save Notes
          </Button>
        </DialogContent>
      </Dialog>
    </div>
  )
}
